version: '3'
services:
  app:
    container_name: app
    build:
      context: .
    working_dir: /opt/www
    entrypoint: [ "php", "bin/hyperf.php", "server:watch" ]
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
